### PR TITLE
Issue #66: Throw an exception if message can not be written

### LINKED ISSUE #66: Throw an exception if message can not be written

### PR DESCRIPTION
**Pull request by tim-bezhashvyly**
Closes #66.

### CODE REVIEW

File: tests/Unit/Suites/FileQueueTest.php [hunk 1]
```diff
@@ -33,6 +34,16 @@ class FileQueueTest extends \PHPUnit_Framework_TestCase
      */
     private $mockMessageReceiver;
 
+    /**
+     * @var bool
+     */
+    private static $diskIsFull = false;
```
Comment (Schrank) [inline tests/Unit/Suites/FileQueueTest.php]: do you want to make this consistens with https://github.com/lizards-and-pumpkins/lib-queue-backend-filesystem/pull/68/files#diff-d433afdf8386f9b63e7c430578310a36R85 and put it into setUp?

Comment (tim-bezhashvyly) [inline tests/Unit/Suites/FileQueueTest.php]: Isn't it already there?
